# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_exp',
                'doc_host': 'https://harveyng.github.io',
                'git_url': 'https://github.com/harveyng/nbdev_exp',
                'lib_path': 'actors'},
  'syms': {'actors.core': {'actors.core.foo': ('core.html#foo', 'actors/core.py')}}}
